### PR TITLE
Added getCreationTime(Path) to KfsAccess

### PR DESCRIPTION
**Pull request by kstinsonqc**
Adds getCreationTime method to KfsAccess.

@mikeov @mckurt @zimmix

### CODE REVIEW

**Comment by mikeov** [comment]
I think that it would make more sense to fix  KfsFileAttr and stat(),  by ensuring that java KfsFileAttr has all fields that the c++ equivalent has, use stat() call, and deprecate all accessor methods that fetch single fields of file attribute, rather than creating a new one.

**Comment by mikeov** [comment]
Also please change KfsClientImpl::ReadDirectory() / DirectoryIterator() / kfs_readdirplus() to pass all fields while you're on this.

**Comment by mikeov** [comment]
And for file attributes report chunkCount()

**Comment by kstinsonqc** [comment]
PR update to undo the addition of getCreationTime() in favor of exposing more of the client's KfsFileAttr files to KfsAccess's version.

**Pull request merged**
