### PR TITLE
Debian packaging

### PR DESCRIPTION
**Pull request by onlyjob**
In process of QFS evaluation I prepared a working draft of Debian packaging.

### CODE REVIEW

**Comment by fsareshwala** [comment]
Hi there,

Apologies for the late response on this pull request. We're still interested in it. Since it's been a while since you pushed your pull request up, do you want to review it again and see if it needs some adjustments before we review it?

**Comment by onlyjob** [comment]
I see there were some releases since I did work on packaging. Update would be necessary though probably a minor one. Unfortunately I won't be able to justify the effort unless you would be willing to sponsor it...

**Comment by fsareshwala** [comment]
Totally understand. Note that we are working with BigTop to get qfs packaged up for debian and rpm sources in a much better way than what is in the qfs contrib currently. Ideally, we would have the rpm and debian packaging identical.

Another option is to bring in the BigTop packaging that we're doing into the qfs contrib as well. So that I can judge the situation better, can you elaborate more on what you mean regarding sponsoring it?

**Comment by onlyjob** [comment]
What is BigTop?

> what you mean regarding sponsoring it?

You can engage me for packaging by purchasing some support hours through http://raid6.com.au/services

**Comment by fsareshwala** [comment]
Ah I see. We really, really appreciate your contribution. However, at this time, we can't sponsor your packaging. I'm sorry.

I'll close this pull request out in the meantime. Thank you so much! Please feel free to submit another pull request should you have any other changes you wish to make. Thank you again!

**Comment by onlyjob** [comment]
> We really, really appreciate your contribution.

Thank you for your kind words but I really doubt that. :(

> I'll close this pull request out in the meantime.

Why didn't you merge it?? It will take a while to do it again if you throw away effort like this.
Once merged as-is only few corrections are needed to update to current version.
Even as it is this commit is a big improvement over incompetent packaging in `contrib`.

**Comment by fsareshwala** [comment]
Oh, I'm sorry. I assumed you were withdrawing your contribution for some reason. I'll be happy to merge it if you aren't. Sorry about the confusion. Your pull request does make the packaging in `contrib` much better.

**Comment by onlyjob** [comment]
Thanks! :) Hopefully someone will have a chance to update the packaging.
I'm no longer using QFS so I have little incentive to continue working on it (but I might be available for hire). FYI I would have closed my pull request if I had intention to withdraw my contribution. I hope Debian packaging will be useful. Thanks for merging.

**Comment by fsareshwala** [comment]
Absolutely! Thank you again for your contribution.

Quantcast is working to engage the community and keep things active. My apologies it took so long to get it merged. It shouldn't take so long in the future.

**Comment by teodor-pripoae** [comment]
Hi @fsareshwala 

Is everything ok with the debian packaging made by @onlyjob ? I also created a few scripts for debian packaging a few months ago starting from @onlyjob  ones. If any work is needed I'm happy to contribute them. 

I remember there were a few issues at the beginning but I can't easy remember which. Also I created a few scripts for packaging qfs metaserver/chunkserver/client/webui inside docker images.

**Comment by fsareshwala** [comment]
Hi @teodor-pripoae, are you seeing any specific issues? We are currently working on integrating QFS into BigTop and have contributed some packaging there for it. You can try and use that to get some quality packages out.

**Comment by teodor-pripoae** [comment]
Is there any source where I can fetch the generated deb files ? It looks I started from a different version, not from @onlyjob files though.

Also, will it be only one deb with all files ? With my scripts I was creating one deb for each of metaserver/chunkserver/client cli/webui/libKFS.

**Comment by fsareshwala** [comment]
The packaging that @onlyjob did produces multiple deb files. The packaging we've done for bigtop also does the same. You can generate some of those packages by cloning the [bigtop](http://bigtop.apache.org) and running `./gradlew toolchain qfs-deb`. Let me know if that helps :).

**Pull request merged**
