### PR TITLE
codecov.io: use continuous code coverage tools to ensure test coverag…

### PR DESCRIPTION
**Pull request by mckurt**
…e remains high (QFS-259)

### CODE REVIEW

**Comment by mckurt** [comment]
Real coverage that considers all src/cc/ folder is 0.37%. I'm not sure why it generated this particular report for src/cc/test/ folder only. I'll investigate later.

**Comment by fsareshwala** [comment]
@mckurt were you able to look into why the coverage report is showing the wrong information?

**Comment by fsareshwala** [comment]
@mckurt I've created https://quantcast.atlassian.net/browse/QFS-308 to address this.

**Comment by mckurt** [comment]
Yes, I contacted them a couple of days ago, but still haven't heard back. It's good that we have the ticket. I'll get back to this soon.

**Pull request merged**
